---
- name: Installing iptables-persistent
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iptables-persistent

- name: Allow all incoming ssh traffic
  iptables:
    chain: INPUT
    action: insert
    jump: ACCEPT
    destination_port: 22
    protocol: tcp
  become: yes

- name: Accept and allow all traffic destined to port 80
  iptables:
    chain: INPUT
    action: append
    jump: ACCEPT
    destination_port: 80
    protocol: tcp
  become: yes

- name: Accept and allow all traffic destined to port 443
  iptables:
    chain: INPUT
    action: append
    jump: ACCEPT
    destination_port: 443
    protocol: tcp
  become: yes
  
- name: Allowing Loopback Traffic
  iptables:
    chain: INPUT
    action: insert
    jump: ACCEPT
    in_interface: lo
  become: yes

- name: Allowing DNS tcp Traffic
  iptables:
    chain: INPUT
    action: append
    jump: ACCEPT
    destination_port: 53
    protocol: tcp
  become: yes

- name: Allowing DNS tcp Traffic
  iptables:
    chain: INPUT
    action: append
    jump: ACCEPT
    destination_port: 53
    protocol: udp
  become: yes

#- name: Set DROP as base policy
#  iptables:
#    chain: INPUT
#    policy: DROP
#  register: set_policy

- name: Saving the rules for REBOOT
  shell: /etc/init.d/iptables-persistent save

